// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkerBookingSystem.Data;

#nullable disable

namespace WorkerBookingSystem.Migrations
{
    [DbContext(typeof(WorkerBookingContext))]
    [Migration("20260517120000_AddWorkerProfilesAndReviews")]
    partial class AddWorkerProfilesAndReviews
    {
    }
}
